### ISSUE TITLE
Удали хранилища

### ISSUE THREAD

**Issue by melekhine** [flakessp/WikiMeteor#1]
Удали, пожалуйста, этот и вот этот https://github.com/flakessp/super-centenarians репозитории.

**Comment by flakessp** [comment]
Без вопросов, а что тут за секретная информация хранится ? )

**Comment by melekhine** [comment]
Нет, просто глаз мозолят.

Или они тебе нужны? Я думаю, что ты тоже в них не заинтересован.

**Comment by melekhine** [comment]
ПРОШУ!
